### ISSUE TITLE
Backend API Ruby Testing: Seed projects hasn't .env file

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-community/auth0-ruby-api-samples#4]
The project:
01-authorization-rs256 doesn't include the .env file

![image](https://user-images.githubusercontent.com/26749061/29173634-eab87b46-7db1-11e7-8c69-bb84a5414abb.png)

**Comment by Amialc** [comment]
Related issue: AUTH-4197

**Comment by aaguiarz** [comment]
@alexisluque please add a .env.example file and mention that in the readme
