### ISSUE TITLE
Missing .env File with the Auth0 variables

### ISSUE THREAD

**Issue by rafanog** [auth0-community/auth0-ruby-api-samples#7]
Sample downloaded doesn't have the environment variables file described on the README.md's instructions to execute it:
![image](https://user-images.githubusercontent.com/15782359/34218672-2ce1073c-e585-11e7-8cd9-ac56f1fcba83.png)

**Comment by aaguiarz** [comment]
Fixed in a5ad75de9069569cfe72d42f369633fa4918824d
